on:
  push:
    paths:
      - 'pom.xml'
      - 'settings.xml'
      - '.mvn/maven.config'
      - '.github/workflows/deploy.yml'
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - env:
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY_OWNER }}
          GITHUB_REPOSITORY_OWNER: ${{ env.GITHUB_REPOSITORY_OWNER }}
        run: |
          mvn help:effective-settings -Drepo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f 2) -Downer=${GITHUB_REPOSITORY_OWNER}
      - run: echo "::set-output name=PUBLIC_PAT::$(wget http://softalks.github.io/public.PAT)"
        id: softalks
      - uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
              "id": "upstream-repository",
              "username": "${{ secrets.GITHUB_TOKEN }}",
              "password": "${{ secrets.GITHUB_TOKEN }}"
            }, {
              "id": "softalks",
              "username": "${{ steps.softalks.outputs.PUBLIC_PAT }}",
              "password": "${{ steps.softalks.outputs.PUBLIC_PAT }}"
            }]
      - env:
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY_OWNER }}
          GITHUB_REPOSITORY_OWNER: ${{ env.GITHUB_REPOSITORY_OWNER }}
        run: |
          mvn help:effective-settings -Drepo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f 2) -Downer=${GITHUB_REPOSITORY_OWNER}
      - env:
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY_OWNER }}
          GITHUB_REPOSITORY_OWNER: ${{ env.GITHUB_REPOSITORY_OWNER }}
        run: |
          mvn deploy -Drepo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f 2) -Downer=${GITHUB_REPOSITORY_OWNER}
